chromadb: # this is the settings for the vector database, persist_directory and collection_name are configurable
  persist_directory: /media/disk2/HSW/Django/LLM/chroma-db
  collection_name: slco1b1_collection
  # collection_name: test_queries_subset
  # collection_name: cpic_data
  # collection_name: empty

ollama:
  embedding_model_name: all-mpnet-base-v2
  chat_model_name: llama3.1
  chat_search_type: mmr   # mmr or similarity
  chat_search_k: 6        # number of best resources to pickup
